# Generated by Django 6.0.1 on 2026-02-01 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_path', models.TextField(unique=True)),
                ('file_name', models.CharField(max_length=255)),
                ('folder', models.TextField()),
                ('size', models.BigIntegerField()),
                ('created_at', models.DateTimeField()),
            ],
        ),
    ]
