# Generated by Django 6.0.1 on 2026-02-01 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0003_alter_photo_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='city',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='photo',
            name='country',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
