# Generated by Django 6.0.1 on 2026-02-01 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0004_photo_city_photo_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='search_text',
            field=models.TextField(blank=True),
        ),
    ]
